version: 2

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  apt_packages:
    - libgmp3-dev

python:
  version: "3.9"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
