version: 2

sphinx:
  configuration: docs/conf.py

build:
  apt_packages:
    - libgmp3-dev

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
