version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - libgmp3-dev
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
