version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - libgmp3-dev
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install poetry
      - poetry self add poetry-plugin-export
      - poetry export -f requirements.txt --output requirements.txt --without-hashes -E docs -E ledger

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
