IDENTIFIER: /[a-zA-Z_][a-zA-Z_0-9]*/

start: type
     | struct

type: "core" "::" core_value

core_value: "felt" "252" -> type_felt
          | "integer" "::" "u" INT -> type_uint
          | "option" "::" "Option" "::" "<" core_value ">" -> type_option
          | "()" -> type_unit

struct: (IDENTIFIER "::")+ "<" type ">"


%import common.INT
%import common.WS
%ignore WS
