name: Run scheduled tests with multiple RPC versions

on:
  workflow_dispatch:

jobs:
  dispatch:
    name: Dispatch (RPC ${{ matrix.rpc_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rpc_version: "v0_8"
            # TODO: Run once compatibility tests are available
            # starknet_py_version: "0.26.0"
            # starknet_jvm_version: "x.y.z"
            # starknet_swift_version: "x.y.z"
          - rpc_version: "v0_9"
            # TODO: Run once compatibility tests are available
            # starknet_py_version: "0.28.1"
            # starknet_jvm_version: "x.y.z"
            # starknet_swift_version: "x.y.z"
          - rpc_version: "v0_10"
            starknet_py_version: "compatibility-tests"
            # TODO: Run once compatibility tests are available
            # starknet_jvm_version: "x.y.z"
            # starknet_swift_version: "x.y.z"

    steps:
      - uses: actions/checkout@v4

      - name: Dispatch starknet.py workflow
        if: matrix.starknet_py_version != ''
        uses: ./.github/actions/dispatch-compatibility-tests
        with:
          repo: software-mansion/starknet.py
          ref: ${{ matrix.starknet_py_version }}
          rpc_version: ${{ matrix.rpc_version }}
          gh_token: ${{ secrets.CI_DISPATCH_TOKEN }}

      - name: Dispatch starknet-jvm workflow
        if: matrix.starknet_jvm_version != ''
        uses: ./.github/actions/dispatch-compatibility-tests
        with:
          repo: software-mansion/starknet-jvm
          ref: ${{ matrix.starknet_jvm_version }}
          rpc_version: ${{ matrix.rpc_version }}
          gh_token: ${{ secrets.CI_DISPATCH_TOKEN }}

      - name: Dispatch starknet.swift workflow
        if: matrix.starknet_swift_version != ''
        uses: ./.github/actions/dispatch-scheduled-tests
        with:
          repo: software-mansion/starknet.swift
          ref: ${{ matrix.starknet_swift_version }}
          rpc_version: ${{ matrix.rpc_version }}
          gh_token: ${{ secrets.CI_DISPATCH_TOKEN }}
