name: Matrix Setup

on:
  workflow_call:
    outputs:
      python-versions:
        description: 'A JSON array of Python versions based on the event type'
    inputs:
      event_type:
        required: true
        type: string

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    steps:
    - name: Set Python versions based on event type
      id: set-python-version
      run: |
        if [ "${{ inputs.event_type }}" == "pull_request" ]; then
          echo "::set-output name=python-versions::$(echo -n '["3.10", "3.12"]')"
        else
          echo "::set-output name=python-versions::$(echo -n '["3.8", "3.9", "3.10", "3.11", "3.12"]')"
        fi