name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          exempt-all-pr-assignees: true
          exempt-issue-labels: 'pinned'
          exempt-pr-labels: 'pinned'
          stale-issue-message: 'This issue is stale because it has not received any activity in the last 30 days. Remove stale label or add a comment, otherwise it will be closed in 5 days.'
          close-issue-message: 'This issue was closed because it has been stale for 5 days with no activity.'
          days-before-issue-stale: 30
          days-before-issue-close: 5
          stale-pr-message: 'This PR is stale because it has not received any activity in the last 30 days. Remove stale label or add a comment, otherwise it will be closed in 5 days.'
          close-pr-message: 'This PR was closed because it has been stale for 5 days with no activity.'
          days-before-pr-stale: 30
          days-before-pr-close: 5
